### ISSUE TITLE
support JSONL format (JSON Lines)

### ISSUE THREAD

**Issue by ehartford** [rioj7/vscode-json-validate#5]
please support jsonl format (one object per line)

```
{"id":1}
{"id":2}
{"id":3}
```

**Comment by rioj7** [comment]
@ehartford

Is `jsonl` the languageID of the file?

Does `jsonl` allow comments at the end of the line?

If it is embedded JSON we need an extra property for a block definition in the setting:

* `"format"` : possible values `"json"`, `"jsonc"`, `"jsonl"`

`"allowComments": true` is synonym of `"format": "jsonc"`

**Comment by ehartford** [comment]
Comments are not permitted in jsonl

**Comment by ehartford** [comment]
The file extension is .jsonl

Myfile.json

```
[
  {"id":1},
  {"id":2},
  {"id":3}
]
```

It's equivalent to

Myfile.jsonl

```
{"id":1}
{"id":2}
{"id":3}
```

**Comment by ehartford** [comment]
Advantage of jsonl is you can stream it one line at a time and each line is a verifiable Json object so you don't have to load the whole file into memory

**Comment by rioj7** [comment]
@ehartford VSC does not work with extensions, it uses languageIDs, you can assign any file extension any languageID.

what does the status line say when you have a JSONL file current?

According to https://marketplace.visualstudio.com/items?itemName=Alpha4.jsonl the languageID is `jsonl`

**Comment by rioj7** [comment]
@ehartford try v1.5.0
